### ISSUE TITLE
Implement creating .txt 
-files

### ISSUE THREAD

**Issue by micha003** [micha003/Vokabeltrainer#3]
I need to implement the creation of .txt-files, because it's necessary to save the KK's

**Comment by micha003** [comment]
The first step is done with the FileSaver.js lib! _Yay!_ :)

**Comment by micha003** [comment]
I made some progress in the project. The newest changes will be viewed in the dev-js branch.

**Comment by micha003** [comment]
It is creating a .txt-file, when I press the button, but only the last created KK is in the file. The next step is to fix it :)

**Comment by micha003** [comment]
Now remains only the content of the files, which should be fixed, because the commas are annoying and should be deleted.

**Comment by micha003** [comment]
When Issue #10 and #11 are fixed, then this issue will be closed.

**Comment by nieopierzony** [comment]
👻
